replicatedhq/kURL-testgrid

- tgapi/deploy/Dockerfile
- tgrun/Dockerfile
fixes build error:
```
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```
> Add go.* files to docker build

- tgapi/pkg/testinstance/testinstance.go
It did not, in fact, work.
2022-09-13T14:49:38.569Z	ERROR	handlers/ref_start.go:119	failed to insert: pq: INSERT has more target columns than expressions
> fix parameter count for testrun creation

- tgrun/pkg/runner/vmi/embed/testhelpers.sh
this new test help function prints the log for all pods in the longhorn-system namespace.
> chore: added function to dump longhorn logs

- deploy/tg-script.sh
changing
```
apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
name: 2e7f363
spec:
kubernetes:
version: 1.23.15
serviceCIDR: 172.19.0.0/16
docker:
version: 20.10.17
weave:
version: 2.8.1-20221122
podCIDR: 172.18.0.0/16
openebs:
version: 3.3.0
isLocalPVEnabled: true
localPVStorageClassName: default
```
to
```
apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
name: 1c12ac6
spec:
kubernetes:
version: 1.25.5
serviceCIDR: 172.19.0.0/16
weave:
version: 2.8.1-20221122
podCIDR: 172.18.0.0/16
openebs:
version: 3.3.0
isLocalPVEnabled: true
localPVStorageClassName: default
containerd:
version: 1.6.12
```
> Use k8s 1.25 and containerd

- tgrun/pkg/runner/vmi/embed/runcmd.sh
Support bundle collection fails in airgap tests with the following error:
```
2023-01-30 12:52:08+00:00 kurl install failed
2023-01-30 12:52:08+00:00 nullnullcollecting support bundle
Error: failed to load support bundle spec: failed to get spec from URL: execute request: Get "https://kots.io": dial tcp 172.67.183.104:443: connect: connection refused
```
https://testgrid.kurl.sh/run/STAGING-release-v2023.01.23-0-0be41f75-20230130102645?kurlLogsInstanceId=iczzwxxbjuihopco&nodeId=iczzwxxbjuihopco-initialprimary#L0
> feat: collect support bundle in airgapped tests

- tgrun/pkg/runner/vmi/embed/common.sh
The upgrade timeout in the primary node is 45 minutes. This PR increases the timeout used in the worker node. This is the timeout for the primary node to report as "done" (i.e. finished).
Read comments [here](https://app.shortcut.com/replicated/story/69495/longhorn-to-rook-test-grid-times-out) to understand the context.
> chore: increase timeout for "primary node is done".

- tgrun/pkg/runner/vmi/embed/runcmd.sh
Recent [staging-daily test](https://testgrid.kurl.sh/run/STAGING-daily-10680f4-2023-02-23T01:28:57Z) for **rook-upgrade-to-15** run were failing due to not having enough time to perform the upgrade. This PR bumps the upgrade timeout. The drawback is that these tests will take longer BUT they will pass.
> Bump timeout on upgrades to 60mins

- tgrun/pkg/runner/vmi/embed/testhelpers.sh
Implement two functions, one that installs a sample application on the cluster and other that attempts to customize it after the cluster has been upgraded.
The idea is that after the install we will deploy the kots application and customize it, once the cluster has been upgraded we check if the customization is still there and then we attempt to customize it once more. If Kots is not working properly after the cluster upgrade the new customization won't take effect.
- Is it OK to have this sample application living in the stable vendor portal ?
- How can we forward the license from the Github action to the VM where the the script runs ?
- We might need to change this to download the app air-gap bundle due to docker hub rate limit.
```
ubuntu@ip-172-31-61-90:~$ ./install.sh
attempting to …
```
> chore: adding functions to test kots application installs and updates.

- tgrun/pkg/runner/vmi/embed/testhelpers.sh
This was working fine on Mac but it does not work the same on Linux because we need to add the quotes.
> chore: add missing quotes on echo command argument.

- tgrun/pkg/runner/vmi/embed/runcmd.sh
- tgrun/pkg/runner/vmi/embed/testhelpers.sh
disabling yum repos in the pre install script is too late and the testgrid setup script is failing with error
https://testgrid.kurl.sh/run/STAGING-release-v2023.03.21-0-53077927-20230327232555?kurlLogsInstanceId=bbockuwlmvogoooe&nodeId=bbockuwlmvogoooe-initialprimary#L0
```
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
```
this will disable yum repos and add convenience functions for installing yum packages prior to disabling.
> feat: disable yum repos on airgap installs

- tgrun/pkg/runner/vmi/embed/testhelpers.sh
kubectl kots command, at least on v1.57.0, requires the namespace to be specified in the command line (this is not true in the newest version).
due to its absense we have a few storage migration testgrids failing with the following error:
attempting to customize kurl integration test application. Error: failed to validate namespace: namespace is required
+ echo 'failed to customize kurl integration test application.'
+ exit 1
> bug: add --namespace flag to kubectl kots command

- tgrun/pkg/scheduler/scheduler.go
- tgrun/pkg/scheduler/types/types.go
Adds `kurl.installerApiEndpoint` and `kurl.upgradeApiEndpoint` properties to the spec to allowing us to more precisely emulate customer environments and test upgrades from previous kurl versions.
> feat: use kurl prod if kurl.installerVersion is set

- tgrun/pkg/runner/vmi/embed/testhelpers.sh
Do not fail immediately if the curl command returns with a non-zero exit code. Retry for the full 25 times.
https://testgrid.kurl.sh/run/ETHAN-20230407-cust-3?kurlLogsInstanceId=wesnqvsdvdkqxleb&nodeId=wesnqvsdvdkqxleb-initialprimary#L0
```
2023-04-07 19:14:50+00:00 kurl integration test application customized, waiting 2m for the deployment.
+ for i in $(seq 1 24)
++ kubectl -n default get service nginx
++ awk '{ print $3}'
++ tail -n1
+ svc_ip=10.96.1.5
++ curl -s 10.96.1.5
+ app_content=
+ local exit_status=7
+ '[' 7 -ne 0 ']'
+ report_failure post_install_script
+ local failure=post_install_script
```
> fix: kots test app failure checking endpoint

- tgrun/pkg/runner/vmi/embed/primarynodecmd.sh
- tgrun/pkg/runner/vmi/embed/runcmd.sh
- tgrun/pkg/runner/vmi/embed/secondarynodecmd.sh
i think this the curl request to download the bundle is failing silently. im hoping this will cause the script to fail
https://testgrid.kurl.sh/run/ETHAN-20230407-cust-6?kurlLogsInstanceId=sskrkvqklnosrkfc&nodeId=sskrkvqklnosrkfc-initialprimary#L0
```
+ curl -sSL -o install.tar.gz https://kurl.sh/bundle/0b47550.tar.gz
2023-04-07 21:44:03+00:00 downloading install bundle
+ '[' -n https://staging.kurl.sh/bundle/d78a3cd.tar.gz ']'
+ echo 'downloading upgrade bundle'
+ curl -sSL -o upgrade.tar.gz https://staging.kurl.sh/bundle/d78a3cd.tar.gz
2023-04-07 21:44:03+00:00 downloading upgrade bundle
...
+ echo 'internet disabled'
+ tar -xzvf install.tar.gz
2023-04-07 21:47:38+00:00 internet disabled
+ local tar_exit_status=0
+ '[' 0 -ne 0 ']'
++ date
+ echo 'running kurl install at '\''Fri Apr  7 …
```
> fix: fail download on error

- tgrun/pkg/runner/vmi/embed/testhelpers.sh
bash -opipefail is causing this statement to fail if the nginx service is not yet deployed.
https://testgrid.kurl.sh/run/ETHAN-20230410-cust-1?kurlLogsInstanceId=dhvljjekchobwprx&nodeId=dhvljjekchobwprx-initialprimary#L0
```
2023-04-10 18:27:13+00:00 kurl integration test application customized, waiting 2m for the deployment.
+ for i in $(seq 1 24)
++ tail -n1
++ awk '{ print $3}'
++ kubectl -n default get service nginx
Error from server (NotFound): services "nginx" not found
+ svc_ip=
+ local exit_status=1
+ '[' 1 -ne 0 ']'
```
> fix: kurl integration test application get nginx service ip

- tgrun/pkg/runner/vmi/embed/runcmd.sh
make airgap bundle url generic so updated app bundle does not necessitate a deployment of testgrid.
> fix: generic kurl integration test app airgap bundle url

- tgrun/pkg/runner/vmi/embed/common.sh
- tgrun/pkg/runner/vmi/embed/primarynodecmd.sh
- tgrun/pkg/runner/vmi/embed/runcmd.sh
- tgrun/pkg/runner/vmi/embed/secondarynodecmd.sh
This is a workaround for the Airgap Download errors we often get
> fix: retry download and untar airgap files

- tgrun/pkg/runner/vmi/embed/testhelpers.sh
With [this change](https://github.com/replicatedhq/kURL/pull/4396) the to version is not longer necessary.
Fixes
https://testgrid.kurl.sh/run/STAGING-release-v2023.04.13-0-360a5007-20230419170331?kurlLogsInstanceId=tkjyagdmrydddvei&nodeId=tkjyagdmrydddvei-initialprimary
```
023-04-19 18:08:36+00:00 ⚙  Upgrading Kubernetes from 1.23.17 to 1.26.3
2023-04-19 18:08:36+00:00 This involves upgrading from 1.23 to 1.24, 1.24 to 1.25, and 1.25 to 1.26.
2023-04-19 18:08:36+00:00 This may take some time.
2023-04-19 18:08:36+00:00 ⚙  Downloading assets required for Kubernetes 1.23.17 to 1.26.3 upgrade
2023-04-19 18:08:36+00:00 The following packages are not available locally, and are required:
2023-04-19 18:08:36+00:00     kubernetes-1.24.12.tar.gz
2023-04-19 18:08:36+00:00 …
```
> fix: omit last version in step upgrade bundle

- tgapi/deploy/Dockerfile
According to https://wiki.debian.org/LTS Stretch release seems to be already out of support.
```
Debian 9 “Stretch” - From July 6, 2020 to June 30, 2022
```
This commit moves the image used by the `tgapi` to Buster (the next LTS release after Stretch):
```
Debian 10 “Buster” from August 1st, 2022 to June 30th, 2024
```
I have managed to build the image and test the binary inside of it:
```
root@d6d076a5d5b1:/# ./tgapi
Usage:
tgapi [flags]
tgapi [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
help        Help about any command
run
Flags:
-h, --help   help for tgapi
Use "tgapi [command] --help" for more information about a command.
root@d6d076a5d5b1:/#
```
I believe this is what is behind these failures: …
> chore: moving tgapi base image to debian buster

- tgrun/pkg/runner/vmi/embed/runcmd.sh
Adds support for writing an installer-spec-file in the preInstallScript phase of the installation. For example:
```yaml
- name: k8s127-rook-override-node-storage
installerSpec:
kubernetes:
version: 1.27.x
containerd:
version: latest
flannel:
version: latest
rook:
version: 1.11.x
registry:
version: latest
kotsadm:
version: latest
ekco:
version: latest
preInstallScript: |
mkdir -p /opt/kurl-testgrid/
echo "apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
name: patch
spec:
rook:
nodes:
- name: \"$(hostname | tr '[:upper:]' '[:lower:]')\"
devices:
- name: vdb" > /opt/kurl-testgrid/patchfile.yaml
```
> feat: support for installer-spec-file

- tgrun/pkg/runner/vmi/embed/runcmd.sh
```
ethan@ethanm-rook-11:~$ curl https://kurl.sh/latest | sudo bash -s  ha asdf
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  340k    0  340k    0     0   187k      0 --:--:--  0:00:01 --:--:--  187k
⚙  Running install with the argument(s): ha asdf
Error: unknown parameter "asdf"
ethan@ethanm-rook-11:~$ curl https://kurl.sh/latest | sudo bash -s "" ha asdf
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  340k    0  340k    0     0   343k      0 --:--:-- --:--:-- --:--:--  342k
⚙  Running install with the argument(s):  ha asdf
Package kurl-bin-utils-v2023.05.08-0.tar.gz already exists, not downloading
SELinux is not installed: no …
```
> fix: empty flag negates the rest of the arguments

- tgrun/pkg/runner/vmi/embed/common.sh
I am seeing mon clock skew detected in some rook upgrade tests. Perhaps our ntp preflight is not sufficient. I want to test this out to see if it fixes things.
> fix: ensure ntp is running

- tgrun/pkg/runner/vmi/embed/common.sh
The rook upgrade tests are failing because the secondary nodes are not staying up long enough.
```
+ i=90
+ '[' 90 -gt 90 ']'
+ sleep 60
2023-05-16 20:54:20+00:00 initprimary not ready
+ true
++ get_initprimary_status
++ primaryNodeId=djovxjtaxxulvdvo-initialprimary
+++ curl -X GET -f https://api.testgrid.kurl.sh/v1/instance/djovxjtaxxulvdvo-initialprimary/node-status
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    30  100    30    0     0    113      0 --:--:-- --:--:-- --:--:--   113
++ response='{"status":"joinCommandStored"}'
+++ echo '{"status":"joinCommandStored"}'
+++ sed 's/{.*status":"*\([0-9a-zA-Z]*\)"*,*.*}/\1/'
++ …
```
> fix: secondary nodes should wait longer for the test to complete

- tgapi/kustomize/overlays/production/deployment.yaml
- tgapi/kustomize/overlays/staging/deployment.yaml
Also set these values the same so that the pods are guaranteed their memory resources (prevents OOMKill when there's enough memory on the host to meet the request, but not enough to reach the limit).
> Update request/limit for memory to 750MiB

- tgrun/pkg/runner/vmi/embed/testhelpers.sh
There is a bug in openssl on rhel 9 https://github.com/openssl/openssl/pull/19606
https://testgrid.kurl.sh/run/pr-4562-80e38c2-minio-2023-06-02T23-17-26Z-k8s-docker-2023-06-05T04:07:01Z?kurlLogsInstanceId=hulpseacqcujxtlv&nodeId=hulpseacqcujxtlv-initialprimary#L0
```
+ export OBJECT_STORE_SECRET_KEY=DnIUahF1u
+ OBJECT_STORE_SECRET_KEY=DnIUahF1u
++ kubectl -n minio get service minio
++ tail -n1
++ awk '{ print $3}'
+ export OBJECT_STORE_CLUSTER_IP=10.96.0.106
+ OBJECT_STORE_CLUSTER_IP=10.96.0.106
+ validate_read_write_object_store rwtest testfile.txt
+ local bucket=rwtest
+ local file=testfile.txt
+ object_store_create_bucket rwtest
+ object_store_bucket_exists rwtest
+ local bucket=rwtest
+ local acl=x-amz-acl:private
++ LC_TIME=en_US.UTF-8
++ TZ=UTC
++ date '+%a, %d %b %Y %T %z'
+ local …
```
> fix: rhel 9 openssl bug

- tgrun/pkg/runner/vmi/embed/testhelpers.sh
This PR does the change to remove ALL ) and not the first one ) found. 
See that in some cases it is not building the right URL, example:
```
curl -fLO 'https://staging.kurl.sh/bundle/10316b5/packages/kubernetes-1.20.15,kubernetes-1.21.14,kubernetes-1.22.17,kubernetes-1.23.17,kubernetes-1.24.14,kubernetes-1.25.10,kubernetes-1.26.5,kubernetes-1.27.2).tar.gz'
```
Fixes: [sc-78141]
> fix installer_kubernets_step_versions to remove all ) so that the URL can be properly build

- tgrun/pkg/runner/vmi/embed/primarynodecmd.sh
- tgrun/pkg/runner/vmi/embed/secondarynodecmd.sh
when there are prompts in the join flow accept them as `yes` to avoid the following:
```sh
2023-07-06 18:44:48+00:00 ✔ Node joined successfully
2023-07-06 18:44:48+00:00 ⚙  Checking proxy configuration with Containerd
2023-07-06 18:44:48+00:00 Skipping test. No HTTP proxy configuration found.
2023-07-06 18:44:48+00:00 2023/07/06 18:44:48 cluster is ready for storage migration.
2023-07-06 18:44:48+00:00     The installer detected both OpenEBS and Rook installations in your cluster. Migration from OpenEBS to Rook
2023-07-06 18:44:48+00:00     is possible now, but it requires scaling down applications using OpenEBS volumes, causing downtime. You can
2023-07-06 18:44:48+00:00     choose to run the migration later if preferred.
2023-07-06 18:44:48+00:00 Would you like to continue with the …
```
> chore: assume yes for join prompts

- migrations/Dockerfile.okteto
- migrations/tables/kustomization.yaml
- migrations/tables/testupgrade.yaml
- tgapi/pkg/cli/api/run.go
- tgapi/pkg/handlers/node_join.go
- tgapi/pkg/handlers/node_upgrade.go
- tgapi/pkg/testinstance/testinstance.go
Adds a new table (so that multiple commands can be stored per test run) and allows setting/getting entries from that table
> enable testgrid to run multi node tests

- tgrun/pkg/runner/loop.go
scheduling can take unbounded time now that we wait for resources
> the cleanup and scheduling loops should run independently

- tgrun/pkg/scheduler/scheduler.go
~Do I know _why_ the Kind is being parsed but APIVersion is not? NO!~
~Does this fix it? YES!~
Does changing the yaml parse library fix it too, with less hackiness? FANTASTIC!
> include hostPreflights apiVersion when it is present

- tgrun/pkg/runner/cleanup.go
- tgrun/pkg/runner/vmi/embed/common.sh
- tgrun/pkg/runner/vmi/embed/runcmd.sh
Why do we need this? Because doing just the Rook 1.0.4 to 1.12.x upgrade takes ~3 hours.
Thankfully, logs are now uploaded while an upgrade is in progress, so this won't prevent us receiving feedback early if something truly does stall out.
> double the node upgrade timeout from 3 to 6 hours

- tgapi/kustomize/overlays/production/disruptionbudget.yaml
- tgapi/kustomize/overlays/staging/disruptionbudget.yaml
Updates Kustomize overlays for PodDisruptionBudgets to meet requirements in EKS 1.25. The API version `policy/v1beta` is deprecated and removed in 1.25.
> Upgrade PDBs to policy/v1 prior to EKS upgrade

- .github/workflows/build-test.yaml
- .github/workflows/deploy.yaml
See:
- https://github.com/replicatedhq/kURL-testgrid/actions/runs/14201240983/job/39788485378
> chore(ci): bump the ubuntu GH runners
